### ISSUE TITLE
Exception when installing into python3 virtualenv

### ISSUE THREAD

**Issue by glennra** [lizardsystem/nensskel#16]
> Collecting pkginfo (from nensskel)
> 
>   Downloading https://files.pythonhosted.org/packages/e6/d5/451b913307b478c49eb29084916639dc53a88489b993530fed0a66bab8b9/pkginfo-1.5.0.1-py2.py3-none-any.whl
> Collecting Cheetah (from nensskel)
>   Downloading https://files.pythonhosted.org/packages/cd/b0/c2d700252fc251e91c08639ff41a8a5203b627f4e0a2ae18a6b662ab32ea/Cheetah-2.4.4.tar.gz (190kB)
>      |████████████████████████████████| 194kB 1.8MB/s 
>     ERROR: Complete output from command python setup.py egg_info:
>     ERROR: Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-install-hurkhkbj/Cheetah/setup.py", line 10, in <module>
>         import SetupTools
>       File "/tmp/pip-install-hurkhkbj/Cheetah/SetupTools.py", line 50
>         except DistutilsPlatformError, x:
>                                      ^
>     SyntaxError: invalid syntax
>     ----------------------------------------
> ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-hurkhkbj/Cheetah/
>

**Comment by reinout** [comment]
Ah, yes. We never updated it for python3.
If you want to test it out, you'll have to use python2.

Note that we've moved away from "paste script" for making such a skeleton, we're using cookiecutter now. See https://github.com/nens?q=cookiecutter

https://github.com/nens/cookiecutter-djangosite-template is the one that best matches nensskel.
